version: "3"

services:
  user-management-postgres:
    container_name: "user-management-postgres"
    image: postgres:16.0
    ports:
      - "6070:5432"
    environment:
      POSTGRES_DB: user-management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 348
  user-management:
    container_name: user-management
    ports:
      - "7750:7750"
    build:
      context: .
      dockerfile: ./cmd/user-management/Dockerfile
    restart: always
    volumes:
      - ./cmd/user-management/config.yaml:/config/config.yaml:ro
    command:
      - -config-path
      - /config/config.yaml
    depends_on:
      - user-management-postgres

  wallet:
    container_name: wallet
    ports:
      - "7751:7751"
    build:
      context: .
      dockerfile: ./cmd/wallet/Dockerfile
    restart: always
    volumes:
      - ./cmd/wallet/config.yaml:/config/config.yaml:ro
    command:
      - -config-path
      - /config/config.yaml

  janus-gateway:
    container_name: janus-gateway
    image: quay.io/hellofresh/janus:3.8.22
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./pkg/janus/apis:/etc/janus/apis