name: Go

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Go linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55.2